# Generated by Django 5.1 on 2024-08-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50, unique=True)),
                ('text', models.TextField(max_length=150)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Why Us Block',
                'verbose_name_plural': 'Why Us Blocks',
                'ordering': ('is_visible', 'position'),
            },
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('category', 'position'), 'verbose_name': 'Dish', 'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='dishcategory',
            options={'ordering': ('position',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
