# Generated by Django 5.1 on 2024-09-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtext',
            name='position',
            field=models.SmallIntegerField(),
        ),
    ]
