# Generated by Django 5.1 on 2024-08-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_whyusblock_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=30)),
                ('is_heading', models.BooleanField(default=False)),
                ('is_paragraph', models.BooleanField(default=False)),
                ('is_unordered_list', models.BooleanField(default=False)),
                ('is_video_link', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.SmallIntegerField(unique=True)),
                ('text', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'About Us Text',
                'verbose_name_plural': 'About Us Texts',
                'ordering': ('position',),
            },
        ),
        migrations.AlterModelOptions(
            name='whyusblock',
            options={'ordering': ('-is_visible', 'position'), 'verbose_name': 'Why Us Block', 'verbose_name_plural': 'Why Us Blocks'},
        ),
        migrations.AlterField(
            model_name='whyusblock',
            name='position',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
