# Generated by Django 5.1 on 2024-09-01 15:25

import django.db.models.deletion
import main_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_eventtext_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to=main_page.models.Chef.get_file_name)),
                ('position', models.SmallIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chef',
                'verbose_name_plural': 'Chefs',
                'ordering': ('is_visible', 'position'),
            },
        ),
        migrations.CreateModel(
            name='ChefSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=20)),
                ('link', models.URLField(max_length=300)),
                ('position', models.SmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.chef')),
            ],
            options={
                'verbose_name': 'Chefs Social',
                'verbose_name_plural': 'Chefs Socials',
                'ordering': ('is_visible', 'position'),
            },
        ),
    ]
