# Generated by Django 5.1 on 2024-08-31 09:59

import main_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_aboutustext_alter_whyusblock_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=main_page.models.Gallery.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
                ('short_description', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
