# Generated by Django 5.1 on 2024-08-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('pk',), 'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
    ]
