# Generated by Django 5.1 on 2024-08-31 20:13

import main_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_gallery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=main_page.models.HeroSlider.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.SmallIntegerField(unique=True)),
                ('heading', models.CharField(max_length=50)),
                ('paragraph', models.TextField(max_length=150)),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Sliders',
                'ordering': ('position', 'is_visible'),
            },
        ),
    ]
