# Generated by Django 5.1 on 2024-08-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_heroslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.SmallIntegerField(unique=True)),
                ('is_paragraph', models.BooleanField(default=True)),
                ('is_unordered_list', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Event Text',
                'verbose_name_plural': 'Event Texts',
                'ordering': ('is_visible', 'position'),
            },
        ),
        migrations.AlterModelOptions(
            name='heroslider',
            options={'ordering': ('-is_visible', 'position'), 'verbose_name': 'Hero Slider', 'verbose_name_plural': 'Hero Sliders'},
        ),
    ]
