# Generated by Django 5.1 on 2024-08-31 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Wrong phone number', regex='^(\\d{3}[- .]?){2}\\d{4}$')])),
                ('message', models.TextField(max_length=500)),
                ('is_processed', models.BooleanField(default=False)),
                ('time_of_receipt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('time_of_receipt',),
            },
        ),
    ]
