# Generated by Django 5.1 on 2024-08-31 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreservation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userreservation',
            name='number_of_people',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userreservation',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
