# Generated by Django 5.1 on 2024-09-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_userreservation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=120)),
                ('message', models.TextField(max_length=500)),
                ('is_processed', models.BooleanField(default=False)),
                ('time_of_receipt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('time_of_receipt',),
            },
        ),
    ]
